"""WebSocket streaming endpoint for AI Debugging Assistant.

Provides real-time token-by-token streaming of AI responses over a
WebSocket connection. The client connects, sends a JSON payload, and
receives tokens as they are generated by the LLM — exactly like
ChatGPT's streaming interface.

Message protocol:
    Client → Server:  JSON with keys: code, stack_trace, filename, language
    Server → Client:  Multiple text frames, one token per frame
                      Final frame is always: {"type": "done", "duration_ms": N}
                      Error frame format:    {"type": "error", "message": "..."}
"""

from __future__ import annotations

import json
import time

from dotenv import load_dotenv
from fastapi import APIRouter, WebSocket, WebSocketDisconnect

load_dotenv()

from backend.app.prompts.debug_prompt import (
    build_debug_system_prompt,
    build_debug_user_prompt,
)
from backend.app.services.ast_parser import ASTParserService
from backend.app.services.llm_service import LLMMessage, LLMService, LLMServiceError
from backend.app.services.stack_trace_parser import StackTraceParser

router = APIRouter(tags=["stream"])

# Shared service instances — created once when the module loads
_stack_parser = StackTraceParser()
_ast_parser = ASTParserService()
_llm_service = LLMService()


# ---------------------------------------------------------------------------
# WebSocket handler
# ---------------------------------------------------------------------------

@router.websocket("/ws/analyze")
async def stream_analysis(websocket: WebSocket) -> None:
    """
    WebSocket endpoint that streams AI debugging analysis token by token.

    Full protocol:
        1. Client connects to ws://localhost:8000/ws/analyze
        2. Client sends JSON:
               {
                 "code": "...",
                 "stack_trace": "...",
                 "filename": "app.py",   (optional)
                 "language": "python"    (optional)
               }
        3. Server streams tokens as plain text frames (one token per frame)
        4. Server sends final JSON frame:
               {"type": "done", "duration_ms": 1234}
        5. Connection closes cleanly

    On any error, server sends:
        {"type": "error", "message": "..."}
    and closes the connection.
    """
    await websocket.accept()

    try:
        # --- Step 1: Receive and parse the request payload -----------------
        raw_payload = await websocket.receive_text()

        try:
            payload = json.loads(raw_payload)
        except json.JSONDecodeError:
            await _send_error(websocket, "Invalid JSON payload.")
            return

        code = payload.get("code", "").strip()
        stack_trace = payload.get("stack_trace", "").strip()
        filename = payload.get("filename")
        language = payload.get("language")

        if not code:
            await _send_error(websocket, "Field 'code' is required and cannot be empty.")
            return
        if not stack_trace:
            await _send_error(websocket, "Field 'stack_trace' is required and cannot be empty.")
            return

        start_time = time.monotonic()

        # --- Step 2: Parse stack trace -------------------------------------
        parsed_trace = _stack_parser.parse(stack_trace)

        # --- Step 3: Parse AST ---------------------------------------------
        parsed_ast = _ast_parser.parse(
            code=code,
            error_line=parsed_trace.error_line,
            filename=filename,
            language=language,
        )

        # --- Step 4: Build prompt ------------------------------------------
        user_prompt = build_debug_user_prompt(
            stack_trace_context=parsed_trace.to_prompt_string(),
            ast_context=parsed_ast.to_prompt_string(),
            raw_code=code,
        )
        system_prompt = build_debug_system_prompt()

        # --- Step 5: Stream tokens to client --------------------------------
        try:
            async for token in _llm_service.stream_response(
                messages=[LLMMessage(role="user", content=user_prompt)],
                system_prompt=system_prompt,
                max_tokens=2000,
            ):
                await websocket.send_text(token)

        except LLMServiceError as exc:
            await _send_error(websocket, f"AI service error: {exc}")
            return

        # --- Step 6: Send done signal --------------------------------------
        duration_ms = int((time.monotonic() - start_time) * 1000)
        await websocket.send_text(json.dumps({"type": "done", "duration_ms": duration_ms}))

    except WebSocketDisconnect:
        # Client closed the connection mid-stream — this is normal behaviour
        pass

    except Exception as exc:
        # Catch-all for unexpected errors — always notify client cleanly
        try:
            await _send_error(websocket, f"Unexpected server error: {exc}")
        except Exception:
            pass  # connection already closed — nothing we can do


async def _send_error(websocket: WebSocket, message: str) -> None:
    """
    Sends a structured error frame to the client and closes the connection.

    Args:
        websocket: The active WebSocket connection.
        message:   Human-readable error description.
    """
    try:
        await websocket.send_text(json.dumps({"type": "error", "message": message}))
        await websocket.close()
    except Exception:
        pass  # connection may already be closed